# Generated by Django 5.2 on 2025-04-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
